///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: music/ingame.aks
/// Generation time: mar 03 nov 2020 22:30:25 CET
///

/// Song 'song_ingame' metadata macros
#define song_ingame_address  0x01D2
#define song_ingame_size     730
#define song_ingame_end      0x4ab

/// Song 'song_ingame' array declaration
extern void song_ingame[song_ingame_size];
