///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: music/menu.aks
/// Generation time: mar 03 nov 2020 22:30:26 CET
///

/// Song 'song_menu' metadata macros
#define song_menu_address  0x0040
#define song_menu_size     403
#define song_menu_end      0x1d2

/// Song 'song_menu' array declaration
extern void song_menu[song_menu_size];
